================================================================================
ROCKDRILL GROUP - LIBRO DE AUDITORÍA Y CONCILIACIÓN 3-EN-1 EN POWER QUERY CLOUD
================================================================================
Este archivo contiene las 3 consultas Power Query M (con origen directo en SharePoint)
para armar el libro de conciliación donde una persona real audita día a día los metrajes.

ESTRUCTURA DE CONSULTAS EN POWER QUERY:
  1. "Consolidado_Operaciones"         -> Extracción SharePoint de Detallados (sin filas de totales, metrajes sinceros)
  2. "Consolidado_Control_Interno"    -> Extracción SharePoint de Control Interno (hojas dd.mm)
  3. "Matriz_Comparativa_Dia_a_Dia"   -> Cruce 1-a-1 instantáneo en memoria (<3s, período auditado activo, 0 errores)

================================================================================
PASO A PASO PARA CONFIGURAR EN EXCEL / POWER BI:
================================================================================
1. Abre tu Excel / Power BI.
2. Ve al 'Editor de Power Query' -> 'Nuevo origen' -> 'Consulta en blanco'.
3. Abre el 'Editor avanzado', pega el código de la CONSULTA 1 y nómbrala EXACTAMENTE:
   Consolidado_Operaciones
4. Crea una segunda 'Consulta en blanco', pega el código de la CONSULTA 2 y nómbrala:
   Consolidado_Control_Interno
5. Crea una tercera 'Consulta en blanco', pega el código de la CONSULTA 3 y nómbrala:
   Matriz_Comparativa_Dia_a_Dia
6. Haz clic en 'Cerrar y aplicar' (o 'Cerrar y cargar en...' -> Tablas).
7. ¡Listo! En la Hoja 3 podrás auditar día por día y turno por turno las coincidencias.

--------------------------------------------------------------------------------
CONSULTA 1: Consolidado_Operaciones (Ver: 01_QUERY_CONSOLIDADO_OPERACIONES.txt)
--------------------------------------------------------------------------------
let
    NombresCanonicos = {
        "FECHA_RAW", "NOMBRE", "PROFUNDIDAD", "LINEA", "INCLINACIÓN", "DESDE", "HASTA", "TURNO (A=1;B=2)", 
        "GRUPO", "METRAJE", "HORAS EXTRAS", "PERFORISTA", "AYUDANTE", "AYUDANTE_1", "TOTAL metraje del dia", 
        "ACUMULADO", "PROYECTADO", "META", "MARCA", "SERIE", "Nº BROCA", "ESTADO DE LA BROCA", "MARCA_1", 
        "Nº ESCARIADOR", "ESTADO DEL ESCARIADOR", "BENTONITA_PRODUCTO", "BENTONITA_CANT.", "BENTONITA_UND.", 
        "PAC_PRODUCTO", "PAC_CANT.", "PAC_UND.", "POLIMERO_PRODUCTO", "POLIMERO_CANT.", "POLIMERO_UND.", 
        "LUBRICANTES_PRODUCTO", "LUBRICANTES_CANT.", "LUBRICANTES_UND.", "CONTROLADOR DE PH Y DUREZA_PRODUCTO", 
        "CONTROLADOR DE PH Y DUREZA_CANT.", "CONTROLADOR DE PH Y DUREZA_UND.", "INHIBIDORES_PRODUCTO", 
        "INHIBIDORES_CANT.", "INHIBIDORES_UND.", "ESTABILIZADOR_PRODUCTO", "ESTABILIZADOR_CANT.", 
        "ESTABILIZADOR_UND.", "OTROS_CLASIFICACIÓN", "OTROS_PRODUCTO", "OTROS_CANT.", "OTROS_UND.", 
        "PETROLEO_CANT.", "PETROLEO_GLN", "Perforación", "Rimado", "Asentado / Retiro de revestimiento (Casing)", 
        "RePerforación", "Preventivo", "Correctivo", "Lavado de sondaje", "Mezclado de lodos", "Manipulación de tuberías", 
        "Acondicionamiento de sondaje", "Cambio de línea", "Recuperación de sondaje por problemas geologicos", 
        "Recuperación de materiales y o maniobras por atrapamiento", "Maniobras por descarga y carga de tuberías (por problemas geologicos)", 
        "Perforación en fallas y/o terrenos altamente fracturados", "Medición de Desviación", "Traslado entre cámaras de perforación", 
        "Cambio de punto de perforacion", "Anclado de máquina de perforación", "Perforación de perno de anclaje", 
        "Cementación de perno de anclaje y fraguado", "Cementado y fraguado de sondaje", "Obturación/Sellado de sondaje con packer", 
        "Sellado de Sondaje", "Inyección de lechada de cemento", "Ensayo Lefranc", "Ensayo Lugeon", "Prueba SPT", 
        "Prueba Shelby", "Pruebas Geotécnicas", "Prueba de nivel freático", "Ensayo Air Lift", "Ensayo Slug Test", 
        "Instalación de piezómetro Casagrande", "Instalación de piezómetro de cuerda vibrante", "Instalación de inclinómetro", 
        "Instalación de piezómetro multinivel", "Instrumentación, toma de presión de agua y caudal", 
        "Prueba de lectura de inclinómetro", "Toma de lecturas cuerda vibrante", "SBO1", "SBO2", "SBO3", "SBO4", "SBO5", 
        "Desate de rocas", "Orden y limpieza", "Recojo de lama", "Poza de sedimentación", "Estandarización y Desestandarización", 
        "Instalación de red de agua o drenaje", "Instalación / Desinstalación de maquina", "Traslado de accesorios", 
        "Auditoría Interna", "Charla, reparto de guardia, llenado de herramientas y reportes", "Espera de repuestos mecánicos", 
        "Espera de materiales e insumos de perforación", "Traslado de personal", "Refrigerio", "Falta de personal", 
        "Paralización por fiestas", "Pare RD/ seguridad", "SBI1", "SBI2", "SBI3", "SBI4", "Voladura", "Falta de agua", 
        "Falta de energía", "Falta de ventilación", "Falta de servicios", "Espera Orden Cliente", "Espera de programa", 
        "Espera de cámara", "Espera de sostenimiento", "Espera de scoop", "Espera de marcado de punto", "Espera de Topografía", 
        "Espera de grúa", "Espera por puebas de permeabilidad y/o ensayos", "Auditoría externa/ Osinergmin", 
        "Capacitación (Externa Cliente)", "Falta de habilitación de cámara o plataforma", "Espera de orden cliente", 
        "Condiciones climáticas", "Inundación", "Paralización por estrés térmico o alta temperatura", "Parada por sismo/microsismo", 
        "Conflicto social", "SBC1", "SBC2", "SBC3", "SBC4", "TIEMPO TOTAL", "TIEMPO EFECTIVO - OPERATIVO", "LOST TIME", 
        "Mantenimiento", "Stand By Operativo", "Stand By Inoperativo", "Stand By Cliente", "RIMADO CON CASING HWT/HQ_DESDE", 
        "RIMADO CON CASING HWT/HQ_HASTA", "RIMADO CON CASING HWT/HQ_METRAJE", "RIMADO CON CASING HWT/HQ_TOTAL", 
        "RE-PERFORACIÓN_DESDE", "RE-PERFORACIÓN_HASTA", "RE-PERFORACIÓN_METRAJE", "RE-PERFORACIÓN_TOTAL", 
        "HOROMETRO_DESDE", "HOROMETRO_HASTA", "HOROMETRO_ACUMULADO", "HOROMETRO_TOTAL", 
        "BITACORA DE MANTENIMIENTO_TRABAJOS REALIZADOS", "BITACORA DE MANTENIMIENTO_REPUESTOS UTILIZADOS", 
        "DESCRIPCIÒN LITOLÓGICA", "COMENTARIOS"
    },

    fn_ProcesarHojaDetallado = (TablaDatos as table, NombreMaquina as text, NombreContrato as text) as table =>
    let
        SaltoAdministrativo = Table.Skip(TablaDatos, 24),
        ColumnasFisicas = List.FirstN(Table.ColumnNames(SaltoAdministrativo), 168),
        Tabla168 = Table.SelectColumns(SaltoAdministrativo, ColumnasFisicas),
        TablaRenombrada = Table.RenameColumns(Tabla168, List.Zip({ColumnasFisicas, NombresCanonicos})),
        
        // 1. FILTRAR FILAS DE TOTALES Y RESÚMENES (Descartar filas sin Turno y sin Perforista, o con palabra TOTAL)
        FiltrarTotalesYVacios = Table.SelectRows(TablaRenombrada, each 
            let
                t = Text.Upper(Text.Trim(Text.From([#"TURNO (A=1;B=2)"] ?? ""))),
                p = Text.Upper(Text.Trim(Text.From([PERFORISTA] ?? ""))),
                f = Text.Upper(Text.Trim(Text.From([FECHA_RAW] ?? ""))),
                n = Text.Upper(Text.Trim(Text.From([NOMBRE] ?? "")))
            in
                not Text.Contains(f, "TOTAL") and 
                not Text.Contains(n, "TOTAL") and 
                not Text.Contains(t, "TOTAL") and 
                not Text.Contains(p, "TOTAL") and
                (t <> "" or p <> "")
        ),
        
        // 2. Relleno hacia abajo de FECHA y SONDAJE
        FillFecha = Table.FillDown(FiltrarTotalesYVacios, {"FECHA_RAW", "NOMBRE"}),
        
        // 3. Normalizar Fecha de Ciclo (Agosto / Setiembre 2026)
        ConFecha = Table.AddColumn(FillFecha, "FECHA", each 
            let
                raw = [FECHA_RAW],
                d = try Date.Day(Date.From(raw, "es-PE")) otherwise (try Number.From(raw) otherwise 26),
                diaVal = if (try Value.Is(d, type number) otherwise false) and d >= 1 and d <= 31 then d else 26,
                mesVal = if diaVal >= 26 then 8 else 9
            in
                #date(2026, mesVal, diaVal), type date
        ),
        
        ConFechaISO = Table.AddColumn(ConFecha, "FECHA_ISO", each Date.ToText([FECHA], "yyyy-MM-dd"), type text),
        ConFechaKey = Table.AddColumn(ConFechaISO, "FECHA_KEY", each Date.ToText([FECHA], "yyyyMMdd"), type text),
        
        // 4. Estandarizar Turno
        ConTurno = Table.AddColumn(ConFechaKey, "TURNO_ESTANDAR", each 
            let t = Text.Upper(Text.Trim(Text.From([#"TURNO (A=1;B=2)"] ?? "A"))) in
            if t = "B" or t = "2" or Text.StartsWith(t, "N") then "B" else "A", type text
        ),
        
        // 5. Normalizar CTR
        ConCTR = Table.AddColumn(ConTurno, "CTR", each 
            let raw = Text.Replace(Text.Replace(NombreContrato, "CTR_", ""), "_", " ") in
            Text.Upper(Text.Trim(raw)), type text
        ),
        
        ConMaquina = Table.AddColumn(ConCTR, "MAQUINA", each Text.Upper(Text.Trim(NombreMaquina)), type text),
        
        // 6. Homologación SAP de Nombres de Máquina
        ConMaquinaHomologada = Table.AddColumn(ConMaquina, "MAQUINA_HOMOLOGADA", each 
            let 
                c = [CTR],
                m = [MAQUINA]
            in 
                if Text.Contains(c, "CHUNGAR") and (m = "XRD90U-03" or m = "XRD90U-003") then "XRD90U-021"
                else if Text.Contains(c, "ANDAYCHAGUA") and m = "LF90DST-002" then "LF90D ST-002"
                else if Text.Contains(c, "ANDAYCHAGUA") and m = "XRD90U-017" then "XRD150U-001"
                else if Text.Contains(c, "CATALINA") and m = "XRD50-003" then "XRD50U-003"
                else if Text.Contains(c, "COBRIZA") and m = "XRD90U-008" then "XRD150U-008"
                else if Text.Contains(c, "INMACULADA") and m = "XRD150-004" then "XRD150USS-004"
                else if Text.Contains(c, "MOROCOCHA") and m = "XRD90USS-002" then "XRD90USS-005"
                else if Text.Contains(c, "TICLIO") and m = "XRD150USS-001" then "XRD150U-007"
                else if Text.Contains(c, "YAULIYACU") and (m = "XRD50USS-001" or m = "XRD50USS-00T") then "XDR50USS-00T"
                else m, type text
        ),
        
        // 7. Clave Única Canónica (YYYYMMDD-MAQUINA-TURNO)
        ConClaveUnica = Table.AddColumn(ConMaquinaHomologada, "ID_CLAVE_UNICA", each 
            [FECHA_KEY] & "-" & [MAQUINA_HOMOLOGADA] & "-" & [TURNO_ESTANDAR], type text
        )
    in
        ConClaveUnica,

    Origen = SharePoint.Files("https://rovheco-my.sharepoint.com/personal/pedro_gamarra_rockdrillgroup_com", [ApiVersion = 15]),
    FiltrarRuta = Table.SelectRows(Origen, each 
        Text.Contains([Folder Path], "Rockdrill_Control_Operaciones") and 
        Text.Contains([Folder Path], "02_Detallado")
    ),
    FiltrarExcel = Table.SelectRows(FiltrarRuta, each 
        ([Extension] = ".xlsx" or [Extension] = ".xlsm") and 
        Text.Contains([Name], "RD.402.P.01.F.01", Comparer.OrdinalIgnoreCase) and
        not Text.StartsWith([Name], "~$")
    ),
    ExcluirCTRs = Table.SelectRows(FiltrarExcel, each 
        not Text.Contains(Text.Upper([Folder Path]), "CTR_CAPITANA") and 
        not Text.Contains(Text.Upper([Folder Path]), "CTR_COLQUIJIRCA")
    ),
    ExtraerCTR = Table.AddColumn(ExcluirCTRs, "Nombre_CTR", each 
        let Partes = Text.Split([Folder Path], "/"), CTR_Folder = List.Select(Partes, (x) => Text.StartsWith(x, "CTR_"))
        in if List.Count(CTR_Folder) > 0 then CTR_Folder{0} else "SIN_CTR"
    ),
    AgruparArchivos = Table.Group(ExtraerCTR, {"Nombre_CTR"}, {
        {"UltimoArchivo", each Table.Max(_, "Date modified")}
    }),
    ExpandirArchivo = Table.ExpandRecordColumn(AgruparArchivos, "UltimoArchivo", {"Content", "Name", "Extension", "Date accessed", "Date modified", "Date created", "Attributes", "Folder Path"}),
    AbrirLibros = Table.AddColumn(ExpandirArchivo, "WorkbookData", each try Excel.Workbook([Content], false) otherwise null),
    ExpandirLibros = Table.ExpandTableColumn(AbrirLibros, "WorkbookData", {"Name", "Data", "Item", "Kind", "Hidden"}, {"SheetName", "Data", "Item", "Kind", "Hidden"}),
    HojasVisibles = Table.SelectRows(ExpandirLibros, each ([Hidden] = false) and ([Kind] = "Sheet")),
    HojasExcluidas = {"ADITIVOS", "GENERAL", "LISTAS", "TIEMPOS", "Tiempos", "RESUMEN", "GRAFICOS", "MAESTRO", "PARAMETROS", "GLOSARIO", "HOJA1", "HOJA2"},
    HojasOperativas = Table.SelectRows(HojasVisibles, each not List.Contains(HojasExcluidas, Text.Upper(Text.Trim([SheetName])))),
    ProcesarHojas = Table.AddColumn(HojasOperativas, "TablaNormalizada", each 
        try fn_ProcesarHojaDetallado([Data], [SheetName], [Nombre_CTR]) otherwise null
    ),
    HojasExitosas = Table.SelectRows(ProcesarHojas, each [TablaNormalizada] <> null and not Table.IsEmpty([TablaNormalizada])),
    ColumnasFinales = Table.ColumnNames(HojasExitosas{0}[TablaNormalizada]),
    ExpandirFinal = Table.ExpandTableColumn(HojasExitosas, "TablaNormalizada", ColumnasFinales),
    LimpiezaSistema = Table.RemoveColumns(ExpandirFinal, {"Content", "Name", "Extension", "Date accessed", "Date modified", "Date created", "Attributes", "Folder Path", "SheetName", "Data", "Item", "Kind", "Hidden", "Nombre_CTR"}),
    ColsFecha = {"FECHA"},
    ColsTexto = {
        "FECHA_RAW", "NOMBRE", "LINEA", "TURNO (A=1;B=2)", "GRUPO", "PERFORISTA", "AYUDANTE", "AYUDANTE_1", 
        "MARCA", "SERIE", "Nº BROCA", "ESTADO DE LA BROCA", "MARCA_1", "Nº ESCARIADOR", "ESTADO DEL ESCARIADOR", 
        "BENTONITA_PRODUCTO", "BENTONITA_UND.", "PAC_PRODUCTO", "PAC_UND.", "POLIMERO_PRODUCTO", "POLIMERO_UND.", 
        "LUBRICANTES_PRODUCTO", "LUBRICANTES_UND.", "CONTROLADOR DE PH Y DUREZA_PRODUCTO", "CONTROLADOR DE PH Y DUREZA_UND.", 
        "INHIBIDORES_PRODUCTO", "INHIBIDORES_UND.", "ESTABILIZADOR_PRODUCTO", "ESTABILIZADOR_UND.", 
        "OTROS_CLASIFICACIÓN", "OTROS_PRODUCTO", "OTROS_UND.", "PETROLEO_GLN", 
        "BITACORA DE MANTENIMIENTO_TRABAJOS REALIZADOS", "BITACORA DE MANTENIMIENTO_REPUESTOS UTILIZADOS", 
        "DESCRIPCIÒN LITOLÓGICA", "COMENTARIOS", "CTR", "MAQUINA", "TURNO_ESTANDAR", "MAQUINA_HOMOLOGADA", "ID_CLAVE_UNICA",
        "FECHA_ISO", "FECHA_KEY"
    },
    TodasLasColumnas = Table.ColumnNames(LimpiezaSistema),
    ColsNumero = List.Difference(TodasLasColumnas, List.Union({ColsFecha, ColsTexto})),
    TiposFecha = List.Transform(ColsFecha, each {_, type date}),
    TiposTexto = List.Transform(ColsTexto, each {_, type text}),
    TiposNumero = List.Transform(ColsNumero, each {_, type number}),
    ListaDeTipos = List.Combine({TiposFecha, TiposTexto, TiposNumero}),
    TablaTipada = Table.TransformColumnTypes(LimpiezaSistema, ListaDeTipos, "es-PE"),
    ReemplazarErrores = Table.ReplaceErrorValues(TablaTipada, List.Transform(ColsNumero, each {_, 0})),
    ReemplazarNulos = Table.ReplaceValue(ReemplazarErrores, null, 0, Replacer.ReplaceValue, ColsNumero)
in
    ReemplazarNulos

--------------------------------------------------------------------------------
CONSULTA 2: Consolidado_Control_Interno (Ver: 02_QUERY_CONSOLIDADO_CONTROL_INTERNO.txt)
--------------------------------------------------------------------------------
// [Ver 02_QUERY_CONSOLIDADO_CONTROL_INTERNO.txt]

--------------------------------------------------------------------------------
CONSULTA 3: Matriz_Comparativa_Dia_a_Dia (Ver: 03_QUERY_MATRIZ_COMPARATIVA_DIA_A_DIA.txt)
--------------------------------------------------------------------------------
let
    Detallados = Consolidado_Operaciones,
    ControlInterno = Consolidado_Control_Interno,

    CIAgrupado = Table.Group(ControlInterno, {"FECHA", "CTR", "MAQUINA", "TURNO_ESTANDAR", "ID_CLAVE_UNICA"}, {
        {"METRAJE_CI", each List.Sum([METRAJE_CI]), type number}
    }),
    CIBuffer = Table.Buffer(CIAgrupado),
    ClavesActivasCI = CIBuffer[ID_CLAVE_UNICA],

    DetalladosAgrupados = Table.Group(Detallados, {"FECHA_ISO", "CTR", "MAQUINA_HOMOLOGADA", "TURNO_ESTANDAR", "ID_CLAVE_UNICA"}, {
        {"METRAJE_DETALLADO", each List.Sum([METRAJE]), type number}
    }),
    DetalladosActivos = Table.SelectRows(DetalladosAgrupados, each List.Contains(ClavesActivasCI, [ID_CLAVE_UNICA])),
    RenombrarDet = Table.RenameColumns(DetalladosActivos, {
        {"FECHA_ISO", "DET_FECHA"},
        {"CTR", "DET_CTR"},
        {"MAQUINA_HOMOLOGADA", "DET_MAQUINA"},
        {"TURNO_ESTANDAR", "DET_TURNO"},
        {"ID_CLAVE_UNICA", "DET_CLAVE"}
    }),
    DetalladosBuffer = Table.Buffer(RenombrarDet),

    MergeTablas = Table.NestedJoin(
        CIBuffer, {"ID_CLAVE_UNICA"},
        DetalladosBuffer, {"DET_CLAVE"},
        "DetalladoData",
        JoinKind.FullOuter
    ),
    ExpandirDet = Table.ExpandTableColumn(MergeTablas, "DetalladoData", 
        {"DET_FECHA", "DET_CTR", "DET_MAQUINA", "DET_TURNO", "DET_CLAVE", "METRAJE_DETALLADO"},
        {"DET_FECHA", "DET_CTR", "DET_MAQUINA", "DET_TURNO", "DET_CLAVE", "DET_METRAJE"}
    ),
    ConFechaFinal = Table.AddColumn(ExpandirDet, "FECHA_FINAL", each [FECHA] ?? [DET_FECHA], type text),
    ConCTRFinal = Table.AddColumn(ConFechaFinal, "CTR_FINAL", each [CTR] ?? [DET_CTR], type text),
    ConMaqFinal = Table.AddColumn(ConCTRFinal, "MAQUINA_FINAL", each [MAQUINA] ?? [DET_MAQUINA], type text),
    ConTurnoFinal = Table.AddColumn(ConMaqFinal, "TURNO_FINAL", each [TURNO_ESTANDAR] ?? [DET_TURNO], type text),
    ConClaveFinal = Table.AddColumn(ConTurnoFinal, "CLAVE_FINAL", each [ID_CLAVE_UNICA] ?? [DET_CLAVE], type text),
    ConMetDet = Table.AddColumn(ConClaveFinal, "MET_DETALLADO", each [DET_METRAJE] ?? 0.0, type number),
    ConMetCI = Table.AddColumn(ConMetDet, "MET_CONTROL_INTERNO", each [METRAJE_CI] ?? 0.0, type number),
    ConDiferencia = Table.AddColumn(ConMetCI, "DIFERENCIA", each [MET_DETALLADO] - [MET_CONTROL_INTERNO], type number),
    ConEstado = Table.AddColumn(ConDiferencia, "ESTADO_AUDITORIA", each 
        let d = Number.Abs([DIFERENCIA]) in
        if d < 0.01 then "✅ CUADRA EXACTO"
        else if [MET_CONTROL_INTERNO] = 0.0 and [MET_DETALLADO] > 0.0 then "⚠️ SOLO EN DETALLADO"
        else if [MET_DETALLADO] = 0.0 and [MET_CONTROL_INTERNO] > 0.0 then "❌ PENDIENTE EN DETALLADO"
        else if d <= 1.50 then "⚠️ DIFERENCIA DECIMAL MENOR (<1.5m)"
        else "❌ DISCREPANCIA REAL", type text
    ),
    ColumnasFinales = Table.SelectColumns(ConEstado, {
        "FECHA_FINAL",
        "CTR_FINAL",
        "MAQUINA_FINAL",
        "TURNO_FINAL",
        "MET_DETALLADO",
        "MET_CONTROL_INTERNO",
        "DIFERENCIA",
        "ESTADO_AUDITORIA",
        "CLAVE_FINAL"
    }),
    RenombrarFinal = Table.RenameColumns(ColumnasFinales, {
        {"FECHA_FINAL", "FECHA"},
        {"CTR_FINAL", "CTR"},
        {"MAQUINA_FINAL", "MAQUINA"},
        {"TURNO_FINAL", "TURNO"},
        {"METRAJE_DETALLADO", "METRAJE_DETALLADOS_M"},
        {"MET_CONTROL_INTERNO", "METRAJE_CONTROL_INTERNO_M"},
        {"DIFERENCIA", "DIFERENCIA_M"},
        {"CLAVE_FINAL", "ID_CLAVE_UNICA"}
    }),
    TablaTipada = Table.TransformColumnTypes(RenombrarFinal, {
        {"FECHA", type text},
        {"CTR", type text},
        {"MAQUINA", type text},
        {"TURNO", type text},
        {"METRAJE_DETALLADOS_M", type number},
        {"METRAJE_CONTROL_INTERNO_M", type number},
        {"DIFERENCIA_M", type number},
        {"ESTADO_AUDITORIA", type text},
        {"ID_CLAVE_UNICA", type text}
    }, "es-PE"),
    OrdenarFilas = Table.Sort(TablaTipada, {{"CTR", Order.Ascending}, {"FECHA", Order.Ascending}, {"MAQUINA", Order.Ascending}, {"TURNO", Order.Ascending}})
in
    OrdenarFilas
