// ==============================================================================
// QUERY 2: Consolidado_Control_Interno (Origen SharePoint en la Nube)
// Nombre de la consulta en Power Query: Consolidado_Control_Interno
// Ubicación: apppowerbi/02_QUERY_CONSOLIDADO_CONTROL_INTERNO.txt
// Descripción: Extrae y compila las pestañas diarias (dd.mm) del libro maestro
// de Control Interno (RD.402.P.01.F.04) desde SharePoint, generando turnos A/B y clave única.
// ==============================================================================
let
    // 1. Origen en SharePoint de la Organización
    Origen = SharePoint.Files("https://rovheco-my.sharepoint.com/personal/pedro_gamarra_rockdrillgroup_com", [ApiVersion = 15]),
    
    // 2. Filtrar archivo oficial de Control Interno dentro de 00_Control_Interno
    FiltrarRuta = Table.SelectRows(Origen, each 
        Text.Contains([Folder Path], "Rockdrill_Control_Operaciones") and 
        Text.Contains([Folder Path], "00_Control_Interno") and
        ([Extension] = ".xlsx" or [Extension] = ".xlsm") and 
        not Text.StartsWith([Name], "~$")
    ),
    ArchivoReciente = Table.Max(FiltrarRuta, "Date modified"),
    Contenido = ArchivoReciente[Content],
    
    // 3. Abrir Libro Excel y seleccionar hojas de fecha diaria (dd.mm)
    WorkbookCI = Excel.Workbook(Contenido, false),
    HojasDiarias = Table.SelectRows(WorkbookCI, each 
        [Kind] = "Sheet" and 
        Text.Length([Name]) <= 6 and 
        Text.Contains([Name], ".") and
        try Value.Is(Number.From(Text.BeforeDelimiter([Name], ".")), type number) otherwise false
    ),
    
    // 4. Procesar cada pestaña diaria
    ProcesarPestanaDiaria = Table.AddColumn(HojasDiarias, "DatosPestana", each 
        let
            nombrePestana = [Name],
            tablaDatos = [Data],
            diaTexto = Text.BeforeDelimiter(nombrePestana, "."),
            mesTexto = Text.AfterDelimiter(nombrePestana, "."),
            diaNum = Number.From(diaTexto),
            mesNum = Number.From(mesTexto),
            anioNum = 2026,
            fechaDt = #date(anioNum, mesNum, diaNum),
            fechaISO = Date.ToText(fechaDt, "yyyy-MM-dd"),
            fechaKey = Date.ToText(fechaDt, "yyyyMMdd"),
            
            SaltoCabecera = Table.Skip(tablaDatos, 9),
            SeleccionCols = Table.SelectColumns(SaltoCabecera, {
                Table.ColumnNames(SaltoCabecera){0},
                Table.ColumnNames(SaltoCabecera){2},
                Table.ColumnNames(SaltoCabecera){6}
            }),
            RenombrarCols = Table.RenameColumns(SeleccionCols, {
                {Table.ColumnNames(SeleccionCols){0}, "CTR_RAW"},
                {Table.ColumnNames(SeleccionCols){1}, "MAQUINA_RAW"},
                {Table.ColumnNames(SeleccionCols){2}, "METRAJE_CI_RAW"}
            }),
            FillCTR = Table.FillDown(RenombrarCols, {"CTR_RAW"}),
            FiltrarFilas = Table.SelectRows(FillCTR, each 
                [MAQUINA_RAW] <> null and 
                [CTR_RAW] <> null and
                not Text.Contains(Text.Upper(Text.From([CTR_RAW])), "TOTAL") and
                not Text.Contains(Text.Upper(Text.From([MAQUINA_RAW])), "TOTAL") and
                not Text.Contains(Text.Upper(Text.From([MAQUINA_RAW])), "EQUIPO") and
                not Text.Contains(Text.Upper(Text.From([MAQUINA_RAW])), "MAQUINA")
            ),
            ConCTRNorm = Table.AddColumn(FiltrarFilas, "CTR", each 
                let raw = Text.Upper(Text.Trim(Text.From([CTR_RAW]))) in 
                if Text.Contains(raw, "AMERICANA") then "CTR_AMERICANA"
                else if Text.Contains(raw, "ANDAYCHAGUA") then "CTR_ANDAYCHAGUA"
                else if Text.Contains(raw, "CATALINA") or Text.Contains(raw, "HUANCA") then "CTR_CATALINA HUANCA"
                else if Text.Contains(raw, "CERRO") then "CTR_CERRO"
                else if Text.Contains(raw, "CHUNGAR") then "CTR_CHUNGAR"
                else if Text.Contains(raw, "COBRIZA") then "CTR_COBRIZA"
                else if Text.Contains(raw, "COLQUISIRI") then "CTR_COLQUISIRI"
                else if Text.Contains(raw, "CONDESTABLE") then "CTR_CONDESTABLE"
                else if Text.Contains(raw, "CUCULI") then "CTR_CUCULI"
                else if Text.Contains(raw, "INMACULADA") then "CTR_INMACULADA"
                else if Text.Contains(raw, "ESTRELLA") then "CTR_LA ESTRELLA"
                else if Text.Contains(raw, "MOROCOCHA") then "CTR_MOROCOCHA"
                else if Text.Contains(raw, "RAURA") then "CTR_RAURA"
                else if Text.Contains(raw, "CRISTOBAL") or Text.Contains(raw, "SAN CRISTOBAL") then "CTR_SAN CRISTOBAL"
                else if Text.Contains(raw, "TAMBOJASA") then "CTR_TAMBOJASA"
                else if Text.Contains(raw, "TICLIO") then "CTR_TICLIO"
                else if Text.Contains(raw, "YAULIYACU") then "CTR_YAULIYACU"
                else if Text.Contains(raw, "YAURICOCHA") then "CTR_YAURICOCHA"
                else raw, type text
            ),
            FiltrarExcluidos = Table.SelectRows(ConCTRNorm, each not Text.Contains([CTR], "COLQUIJIRCA") and not Text.Contains([CTR], "CAPITANA")),
            ConMaquinaHomologada = Table.AddColumn(FiltrarExcluidos, "MAQUINA_HOMOLOGADA", each 
                let 
                    ctr = [CTR],
                    maq = Text.Upper(Text.Trim(Text.From([MAQUINA_RAW])))
                in 
                    if (ctr = "CTR_CHUNGAR" or ctr = "CHUNGAR") and (maq = "XRD90U-03" or maq = "XRD90U-003") then "XRD90U-021"
                    else if (ctr = "CTR_ANDAYCHAGUA" or ctr = "ANDAYCHAGUA") and (maq = "LF90DST-002" or maq = "LF90D ST-002") then "LF90D ST-002"
                    else if (ctr = "CTR_ANDAYCHAGUA" or ctr = "ANDAYCHAGUA") and maq = "XRD90U-017" then "XRD150U-001"
                    else if (ctr = "CTR_CATALINA HUANCA" or ctr = "CATALINA HUANCA") and (maq = "XRD50-003" or maq = "XRD50U-003") then "XRD50U-003"
                    else if (ctr = "CTR_COBRIZA" or ctr = "COBRIZA") and (maq = "XRD90U-008" or maq = "XRD150U-008") then "XRD150U-008"
                    else if (ctr = "CTR_INMACULADA" or ctr = "INMACULADA") and (maq = "XRD150-004" or maq = "XRD150USS-004") then "XRD150USS-004"
                    else if (ctr = "CTR_MOROCOCHA" or ctr = "MOROCOCHA") and (maq = "XRD90USS-002" or maq = "XRD90USS-005") then "XRD90USS-005"
                    else if (ctr = "CTR_TICLIO" or ctr = "TICLIO") and (maq = "XRD150USS-001" or maq = "XRD150U-007") then "XRD150U-007"
                    else if (ctr = "CTR_YAULIYACU" or ctr = "YAULIYACU") and (maq = "XRD50USS-001" or maq = "XRD50USS-00T") then "XDR50USS-00T"
                    else maq, type text
            ),
            AgruparTurnos = Table.Group(ConMaquinaHomologada, {"CTR", "MAQUINA_HOMOLOGADA"}, {
                {"FilasMaq", each 
                    let 
                        conIndice = Table.AddIndexColumn(_, "IndiceTurno", 1, 1),
                        conTurno = Table.AddColumn(conIndice, "TURNO_ESTANDAR", each if [IndiceTurno] = 1 then "A" else "B", type text)
                    in 
                        conTurno, type table
                }
            }),
            ExpandirTurnos = Table.Combine(AgruparTurnos[FilasMaq]),
            ConMetraje = Table.AddColumn(ExpandirTurnos, "METRAJE_CI", each 
                let v = [METRAJE_CI_RAW] in 
                if v = null or v = "" or v = "-" then 0.0 
                else try Number.From(v, "es-PE") otherwise 0.0, type number
            ),
            ConFecha = Table.AddColumn(ConMetraje, "FECHA", each fechaISO, type text),
            ConFechaKey = Table.AddColumn(ConFecha, "FECHA_KEY", each fechaKey, type text),
            ConClave = Table.AddColumn(ConFechaKey, "ID_CLAVE_UNICA", each 
                [FECHA_KEY] & "-" & [MAQUINA_HOMOLOGADA] & "-" & [TURNO_ESTANDAR], type text
            )
        in
            ConClave
    ),
    TablaConsolidadaCI = Table.Combine(ProcesarPestanaDiaria[DatosPestana]),
    ColumnasFinales = Table.SelectColumns(TablaConsolidadaCI, {
        "FECHA", "CTR", "MAQUINA_HOMOLOGADA", "TURNO_ESTANDAR", "METRAJE_CI", "ID_CLAVE_UNICA"
    }),
    RenombrarColsFinal = Table.RenameColumns(ColumnasFinales, {{"MAQUINA_HOMOLOGADA", "MAQUINA"}})
in
    RenombrarColsFinal
