// ==============================================================================
// QUERY 3: Matriz_Comparativa_Dia_a_Dia (Ultra-Rápida en Memoria y Cero Errores)
// Nombre de la consulta en Power Query: Matriz_Comparativa_Dia_a_Dia
// Ubicación: apppowerbi/03_QUERY_MATRIZ_COMPARATIVA_DIA_A_DIA.txt
// Descripción: Cruza en memoria los metrajes de Control Interno vs Detallados
// acotado al período auditado activo (elimina filas futuras), con Table.Buffer para
// ejecución instantánea (<3s), coalesciendo claves únicas y fechas canónicas.
// ==============================================================================
let
    // 1. Cargar las dos consultas base
    Detallados = Consolidado_Operaciones,
    ControlInterno = Consolidado_Control_Interno,

    // 2. Agrupar Control Interno y retener en Memoria Buffer (610 filas)
    CIAgrupado = Table.Group(ControlInterno, {"FECHA", "CTR", "MAQUINA", "TURNO_ESTANDAR", "ID_CLAVE_UNICA"}, {
        {"METRAJE_CI", each List.Sum([METRAJE_CI]), type number}
    }),
    CIBuffer = Table.Buffer(CIAgrupado),
    
    // Lista de claves auditadas activas en Control Interno
    ClavesActivasCI = CIBuffer[ID_CLAVE_UNICA],

    // 3. Agrupar Detallados y acotar a las claves activas auditadas
    DetalladosAgrupados = Table.Group(Detallados, {"FECHA_ISO", "CTR", "MAQUINA_HOMOLOGADA", "TURNO_ESTANDAR", "ID_CLAVE_UNICA"}, {
        {"METRAJE_DETALLADO", each List.Sum([METRAJE]), type number}
    }),
    DetalladosActivos = Table.SelectRows(DetalladosAgrupados, each List.Contains(ClavesActivasCI, [ID_CLAVE_UNICA])),
    RenombrarDet = Table.RenameColumns(DetalladosActivos, {
        {"FECHA_ISO", "DET_FECHA"},
        {"CTR", "DET_CTR"},
        {"MAQUINA_HOMOLOGADA", "DET_MAQUINA"},
        {"TURNO_ESTANDAR", "DET_TURNO"},
        {"ID_CLAVE_UNICA", "DET_CLAVE"}
    }),
    DetalladosBuffer = Table.Buffer(RenombrarDet),

    // 4. Cruce Instantáneo en Memoria (Full Outer Join sobre tablas bufferizadas)
    MergeTablas = Table.NestedJoin(
        CIBuffer, {"ID_CLAVE_UNICA"},
        DetalladosBuffer, {"DET_CLAVE"},
        "DetalladoData",
        JoinKind.FullOuter
    ),

    // 5. Expandir Columnas de Detallados
    ExpandirDet = Table.ExpandTableColumn(MergeTablas, "DetalladoData", 
        {"DET_FECHA", "DET_CTR", "DET_MAQUINA", "DET_TURNO", "DET_CLAVE", "METRAJE_DETALLADO"},
        {"DET_FECHA", "DET_CTR", "DET_MAQUINA", "DET_TURNO", "DET_CLAVE", "DET_METRAJE"}
    ),

    // 6. Coalescer campos para garantizar cero valores nulos
    ConFechaFinal = Table.AddColumn(ExpandirDet, "FECHA_FINAL", each [FECHA] ?? [DET_FECHA], type text),
    ConCTRFinal = Table.AddColumn(ConFechaFinal, "CTR_FINAL", each [CTR] ?? [DET_CTR], type text),
    ConMaqFinal = Table.AddColumn(ConCTRFinal, "MAQUINA_FINAL", each [MAQUINA] ?? [DET_MAQUINA], type text),
    ConTurnoFinal = Table.AddColumn(ConMaqFinal, "TURNO_FINAL", each [TURNO_ESTANDAR] ?? [DET_TURNO], type text),
    ConClaveFinal = Table.AddColumn(ConTurnoFinal, "CLAVE_FINAL", each [ID_CLAVE_UNICA] ?? [DET_CLAVE], type text),

    // 7. Llenar nulos de metraje con 0.0
    ConMetDet = Table.AddColumn(ConClaveFinal, "MET_DETALLADO", each [DET_METRAJE] ?? 0.0, type number),
    ConMetCI = Table.AddColumn(ConMetDet, "MET_CONTROL_INTERNO", each [METRAJE_CI] ?? 0.0, type number),

    // 8. Calcular Diferencia y Estado de Conciliación
    ConDiferencia = Table.AddColumn(ConMetCI, "DIFERENCIA", each [MET_DETALLADO] - [MET_CONTROL_INTERNO], type number),
    ConEstado = Table.AddColumn(ConDiferencia, "ESTADO_AUDITORIA", each 
        let d = Number.Abs([DIFERENCIA]) in
        if d < 0.01 then "✅ CUADRA EXACTO"
        else if [MET_CONTROL_INTERNO] = 0.0 and [MET_DETALLADO] > 0.0 then "⚠️ SOLO EN DETALLADO"
        else if [MET_DETALLADO] = 0.0 and [MET_CONTROL_INTERNO] > 0.0 then "❌ PENDIENTE EN DETALLADO"
        else if d <= 1.50 then "⚠️ DIFERENCIA DECIMAL MENOR (<1.5m)"
        else "❌ DISCREPANCIA REAL", type text
    ),

    // 9. Seleccionar, Renombrar y Tipar Columnas Finales
    ColumnasFinales = Table.SelectColumns(ConEstado, {
        "FECHA_FINAL",
        "CTR_FINAL",
        "MAQUINA_FINAL",
        "TURNO_FINAL",
        "MET_DETALLADO",
        "MET_CONTROL_INTERNO",
        "DIFERENCIA",
        "ESTADO_AUDITORIA",
        "CLAVE_FINAL"
    }),
    RenombrarFinal = Table.RenameColumns(ColumnasFinales, {
        {"FECHA_FINAL", "FECHA"},
        {"CTR_FINAL", "CTR"},
        {"MAQUINA_FINAL", "MAQUINA"},
        {"TURNO_FINAL", "TURNO"},
        {"MET_DETALLADO", "METRAJE_DETALLADOS_M"},
        {"MET_CONTROL_INTERNO", "METRAJE_CONTROL_INTERNO_M"},
        {"DIFERENCIA", "DIFERENCIA_M"},
        {"CLAVE_FINAL", "ID_CLAVE_UNICA"}
    }),
    TablaTipada = Table.TransformColumnTypes(RenombrarFinal, {
        {"FECHA", type text},
        {"CTR", type text},
        {"MAQUINA", type text},
        {"TURNO", type text},
        {"METRAJE_DETALLADOS_M", type number},
        {"METRAJE_CONTROL_INTERNO_M", type number},
        {"DIFERENCIA_M", type number},
        {"ESTADO_AUDITORIA", type text},
        {"ID_CLAVE_UNICA", type text}
    }, "es-PE"),
    OrdenarFilas = Table.Sort(TablaTipada, {{"CTR", Order.Ascending}, {"FECHA", Order.Ascending}, {"MAQUINA", Order.Ascending}, {"TURNO", Order.Ascending}})
in
    OrdenarFilas
